media:
  input: src/media
  output: /media

content:

  # =========================
  # HOME PAGE (single file)
  # =========================
  - name: home
    label: Home Page
    type: file
    path: src/content/home/index.md
    fields:

      - name: seo
        label: SEO
        type: object
        fields:
          - { name: title, label: SEO Title, type: string }
          - { name: description, label: Meta Description, type: text }
          - { name: og_title, label: OG Title, type: string }
          - { name: og_description, label: OG Description, type: text }
          - { name: og_image, label: OG Image, type: image }

      - name: hero
        label: Hero
        type: object
        fields:
          - { name: headline, label: Headline, type: string }
          - { name: subhead, label: Subhead, type: string }
          - { name: button_label, label: Button Label, type: string }
          - { name: background_image, label: Background Image, type: image }
          - { name: background_image_alt, label: Background Image Alt, type: string }

      - name: philosophy
        label: Philosophy
        type: object
        fields:
          - { name: heading, label: Heading, type: string }
          - { name: text, label: Text, type: rich-text }
          - { name: image, label: Philosophy Image, type: image }
          - { name: image_alt, label: Philosophy Image Alt, type: string }

      - name: couples
        label: For Couples Who
        type: object
        fields:
          - { name: heading, label: Heading, type: string }
          - { name: text, label: Text, type: rich-text }
          - { name: image, label: Couples Image, type: image }

      - name: filmmaker
        label: Filmmaker
        type: object
        fields:
          - { name: heading, label: Heading, type: string }
          - { name: image, label: Filmmaker Image, type: image }
          - { name: text, label: Text, type: rich-text }

      - name: experience
        label: Experience
        type: object
        fields:
          - { name: heading, label: Heading, type: string }
          - { name: text, label: Text, type: rich-text }
          - { name: image, label: Experience Image, type: image }
          - { name: image_alt, label: Experience Image Alt, type: string }

      - name: inquiry_cta
        label: Inquiry CTA
        type: object
        fields:
          - { name: heading, label: Heading, type: string }
          - { name: text, label: Text, type: rich-text }
          - { name: button_label, label: Button Label, type: string }


  # =========================
  # FILMS COLLECTION
  # =========================
  - name: films
    label: Films
    type: collection
    path: src/content/films
    view:
      fields: [ title, featured, order ]
    fields:
      - { name: title, label: Title, type: string }
      - { name: featured, label: Featured on Homepage, type: boolean, default: false }
      - { name: thumbnail, label: Thumbnail Image, type: image }
      - { name: video_url, label: Video URL (Vimeo or YouTube), type: string }
      - { name: order, label: Order, type: number }


  # =========================
  # PAGES COLLECTION
  # =========================
  - name: pages
    label: Pages
    type: collection
    path: src/content/pages
    view:
      fields: [ title ]
    fields:
      - { name: title, label: Title, type: string }
      - { name: layout, label: Layout, type: string, hidden: true, default: layouts/page.njk }
      - { name: body, label: Body, type: rich-text }
      - { name: image, label: Page Image, type: image }
      - { name: image_alt, label: Page Image Alt, type: string }

      - name: seo
        label: SEO
        type: object
        fields:
          - { name: title, label: SEO Title, type: string }
          - { name: description, label: Meta Description, type: text }
          - { name: og_title, label: OG Title, type: string }
          - { name: og_description, label: OG Description, type: text }
          - { name: og_image, label: OG Image, type: image }


  # =========================
  # FOOTER (single file)
  # =========================
  - name: footer
    label: Footer
    type: file
    path: src/content/footer/footer.md
    fields:
      - { name: tagline, label: Tagline, type: string }
      - { name: location_heading, label: Location Heading, type: string }
      - { name: location_body, label: Location Body, type: rich-text }
      - { name: contact_heading, label: Contact Heading, type: string }
      - { name: contact_body, label: Contact Body, type: rich-text }


  # =========================
  # FORMS (single file)
  # =========================
  - name: inquiry_form
    label: Inquiry Form
    type: file
    path: src/content/forms/inquiry.md
    fields:
      - { name: title, label: Form Title, type: string }
      - { name: form_name, label: Form Name, type: string }
      - { name: submit_label, label: Submit Button Label, type: string }

      - name: fields
        label: Fields
        type: list
        fields:
          - { name: label, label: Label, type: string }
          - { name: name, label: Name (no spaces), type: string }
          - { name: type, label: Type, type: string }
          - { name: required, label: Required, type: boolean, default: false }
          - { name: placeholder, label: Placeholder, type: string }