content:
  # =========================
  # HOME PAGE (single file)
  # =========================
  - name: "home"
    label: "Home Page"
    files:
      - name: "home"
        label: "Homepage Content"
        file: "src/content/home/index.md"
        fields:
          - label: "SEO"
            name: "seo"
            widget: "object"
            collapsed: true
            fields:
              - { label: "SEO Title", name: "title", widget: "string", default: "Sylvan Wedding Films | Wedding Videographer in Pittsburgh" }
              - { label: "Meta Description", name: "description", widget: "text" }
              - { label: "OG Title", name: "og_title", widget: "string" }
              - { label: "OG Description", name: "og_description", widget: "text" }
              - { label: "OG Image", name: "og_image", widget: "image" }

          - label: "Hero"
            name: "hero"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Headline", name: "headline", widget: "string" }
              - { label: "Subhead", name: "subhead", widget: "string" }
              - { label: "Button Label", name: "button_label", widget: "string" }
              - { label: "Background Image", name: "background_image", widget: "image" }
              - { label: "Background Image Alt", name: "background_image_alt", widget: "string" }

          - label: "Philosophy"
            name: "philosophy"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Heading", name: "heading", widget: "string" }
              - { label: "Text", name: "text", widget: "markdown" }
              - { label: "Philosophy Image", name: "image", widget: "image" }
              - { label: "Philosophy Image Alt", name: "image_alt", widget: "string" }

          - label: "For Couples Who"
            name: "couples"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Heading", name: "heading", widget: "string" }
              - { label: "Text", name: "text", widget: "markdown" }
              - { label: "Couples Image", name: "image", widget: "image" }

          - label: "Filmmaker"
            name: "filmmaker"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Heading", name: "heading", widget: "string" }
              - { label: "Filmmaker Image", name: "image", widget: "image" }
              - { label: "Text", name: "text", widget: "markdown" }

          - label: "Experience"
            name: "experience"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Heading", name: "heading", widget: "string" }
              - { label: "Text", name: "text", widget: "markdown" }
              - { label: "Experience Image", name: "image", widget: "image" }
              - { label: "Experience Image Alt", name: "image_alt", widget: "string" }

          - label: "Inquiry CTA"
            name: "inquiry_cta"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Heading", name: "heading", widget: "string" }
              - { label: "Text", name: "text", widget: "markdown" }
              - { label: "Button Label", name: "button_label", widget: "string" }

  # =========================
  # FILMS COLLECTION
  # =========================
  - name: "films"
    label: "Films"
    folder: "src/content/films"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured on Homepage", name: "featured", widget: "boolean", default: false }
      - { label: "Thumbnail Image", name: "thumbnail", widget: "image" }
      - { label: "Video URL (Vimeo or YouTube)", name: "video_url", widget: "string" }
      - { label: "Order", name: "order", widget: "number", required: true, hint: "Determines the order in which films appear" }

  # =========================
  # PAGES COLLECTION (including Inquiry)
  # =========================
  - name: "pages"
    label: "Pages"
    folder: "src/content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/page.njk" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Page Image", name: "image", widget: "image", required: false }
      - { label: "Page Image Alt", name: "image_alt", widget: "string", required: false }
      - label: "SEO"
        name: "seo"
        widget: "object"
        collapsed: true
        fields:
          - { label: "SEO Title", name: "title", widget: "string" }
          - { label: "Meta Description", name: "description", widget: "text" }
          - { label: "OG Title", name: "og_title", widget: "string" }
          - { label: "OG Description", name: "og_description", widget: "text" }
          - { label: "OG Image", name: "og_image", widget: "image" }

  # =========================
  # FOOTER
  # =========================
  - name: "footer"
    label: "Footer"
    files:
      - name: "footer"
        label: "Footer Content"
        file: "src/content/footer/footer.md"
        fields:
          - { label: "Tagline", name: "tagline", widget: "string" }
          - { label: "Location Heading", name: "location_heading", widget: "string" }
          - { label: "Location Body", name: "location_body", widget: "markdown" }
          - { label: "Contact Heading", name: "contact_heading", widget: "string" }
          - { label: "Contact Body", name: "contact_body", widget: "markdown" }

  # =========================
  # FORMS
  # =========================
  - name: "forms"
    label: "Forms"
    files:
      - name: "inquiry"
        label: "Inquiry Form"
        file: "src/content/forms/inquiry.md"
        fields:
          - { label: "Form Title", name: "title", widget: "string" }
          - { label: "Form Name", name: "form_name", widget: "string" }
          - { label: "Submit Button Label", name: "submit_label", widget: "string" }
          - label: "Fields"
            name: "fields"
            widget: "list"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Name (no spaces)", name: "name", widget: "string" }
              - label: "Type", name: "type", widget: "select", options: [text, email, textarea]
              - { label: "Required", name: "required", widget: "boolean", default: false }
              - { label: "Placeholder", name: "placeholder", widget: "string", required: false }